### ISSUE TITLE
[!] Error installing PinterestSDK

### ISSUE THREAD

**Issue by KyleJu** [pinterest/ios-pdk#1]
Pre-downloading: `PinterestSDK` from `git@github.com:pinterest/ios-pdk.git`

[!] Error installing PinterestSDK
[!] /usr/bin/git clone git@github.com:pinterest/ios-pdk.git /var/folders/pl/yrk05r2513s5slxl14s3m0tc0000gp/T/d20150723-3313-14c28hb --single-branch --depth 1

Cloning into '/var/folders/pl/yrk05r2513s5slxl14s3m0tc0000gp/T/d20150723-3313-14c28hb'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 
Would anyone know why?

**Comment by garrettmoon** [comment]
You may want to give the https version a try:

https://github.com/pinterest/ios-pdk.git

**Comment by pinbeltzner** [comment]
@KyleJu did that resolve your issue?

**Comment by parkerdonat** [comment]
I tried using this in my pod file instead and it worked:

 'PinterestSDK', :git => 'https://github.com/pinterest/ios-pdk.git'

**Comment by garrettmoon** [comment]
Glad that worked!

**Comment by galu08** [comment]
this help me. Please change the link in the documentation page!

**Comment by brunomcortez** [comment]
thanks, it worked for me!

**Comment by divinebaibhav** [comment]
https://github.com/pinterest/ios-pdk.git
grt !!! it worked !
