### ISSUE TITLE
can not redirect to pinterest app in iOS 9

### ISSUE THREAD

**Issue by Jay-Raparka-Git** [pinterest/ios-pdk#10]
I'm using PDK and want to pin image and method called successfully but response i get is

-canOpenURL: failed for URL: "pinterestsdk.v1://pinit/?client_id=1234&source_url=http%3A%2F%2Fgoogle.com%2Fiphone%2FLAQ_app%2F&app_name=LAQ%20App&image_url=http%3A%2F%2Fcricyard.com%2Fiphone%2FLAQ_app%2Fservice%2Fuserfile%2F0be6e37f52b88bcb71e33ac2f6bc87f8.png&suggested_board_name=LAQ%20App&description=LAQ%20nail%20package%20design" - error: "(null)"

I'm using below method for pining the image.
[PDKPin pinWithImageURL:]

but i get above error.

i have set **pinterestsdk.v1, and also set pinterest** to **LSApplicationQueriesSchemes** property.

I'm using XCode 7 and iOS-9 and i searched about this problem and one answer i found that when my app will approved from reviewing than you can pin the image. But i send mail to you previously than the replay from you that you can test your app but I can't so please give me replay with the solution now what to do? I have to wait for app approve? If yes than can you please tell me the approx time? Because it is very time consuming. I have read your Docs and follow all the steps and my app is in under construction so can't give you a store ID other details i had given. Or else if without approve the app i can test than i follow the code from **iOS-PDK** and it works perfect but i got above error.So please help me on my issue.

i had submit my app for approve but still it not approved or else no replay from your side and till now i have given so much  time for this issue.

So it's my humble request that please help me as soon as possible.

Thanks,
Jay.

**Comment by rcancro** [comment]
This is what you will need to add to your plist:

```
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>pinit</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
                <false/>
            </dict>
        </dict>
    </dict>
    <key>LSApplicationQueriesSchemes</key>
    <array>
        <string>pinterestsdk.v1</string>
    </array>
```

**Comment by Jay-Raparka-Git** [comment]
Thank u @rcancro for your replay

But in my application I have some services with **http:// and some of are https://** so I have done this in my plist

    <key>NSAppTransportSecurity</key>
	    <dict>
		    <key>NSAllowsArbitraryLoads</key>
		    <true/>
	    </dict>
    

and also doing this

    <key>LSApplicationQueriesSchemes</key>
	    <array>
		    <string>pinterestsdk.v1</string>
        </array>

Now what to do?

i hope that  you have the solution for that.

Thank U,
Jay.

**Comment by rcancro** [comment]
I'm not sure what I understand the issue. Are you still having problems with `canOpenURL:`?

It looks like the images coming back from the server are http not https, so I added this to the plist:

```
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>pinterestsdk.v1</string>
	</array>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>pinit</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
				<false/>
			</dict>
			<key>pinimg.com</key>
			<dict>
				<key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
				<false/>
			</dict>
		</dict>
	</dict>
```

That should be all that you need.

**Comment by Jay-Raparka-Git** [comment]
Thank you @rcancro,
But still I got the above problem. I'm stuck and still my application not approved. I didn't get solution for this and too confuse and can't say i could not do this yet. I'm feel so feel so embarrassing that this silly task i did not complete.

sorry to say but now i have no another way
can you please send me just demo for pining image with iOS 9 and made in Xcode 7?

Hope you are happy to help me.

Thank U

**Comment by rcancro** [comment]
Ok, I think I may know what is going on. It looks like you are trying to use the unauthenticated pinit method which redirects to the Pinterest app to create a pin. If you are on the simulator then you wouldn't have the Pinterest app installed so `canOpenURL:` would fail. Have you tried it on a device with Pinterest installed?

I suspect what you want to do is use one of the pin creation methods in `PDKClient`. One of these:

```
- (void)createPinWithImageURL:(NSURL *)imageURL
                         link:(NSURL *)link
                      onBoard:(NSString *)boardId
                  description:(NSString *)pinDescription
                  withSuccess:(PDKClientSuccess)successBlock
                   andFailure:(PDKClientFailure)failureBlock;

- (void)createPinWithImage:(UIImage *)image
                      link:(NSURL *)link
                   onBoard:(NSString *)boardId
               description:(NSString *)pinDescription
                  progress:(PDKPinUploadProgress)progressBlock
               withSuccess:(PDKClientSuccess)successBlock
                andFailure:(PDKClientFailure)failureBlock;
```

These methods will create a pin from your application without any need to redirect to Pinterest.

**Comment by Jay-Raparka-Git** [comment]
Thank U,
and I have done with the device before and it will give same error and now it redirect to the pinterest application and create pin popup will appear but when I select the board it will give me alert with black box and say my AppId is not valid.

now I want to know that what is the difference between `createPinWithImage` and `pinWithImageURL` because both create pin one without obtain oauth and other I don't know and yes why my AppId  is not valid alert I get? I still did not create pin.

**Comment by rcancro** [comment]
`pinWithImageURL` is used when you do not both authenticating the user. It redirects the user to the Pinterest app and provides UI for the user to save a pin.

`createPinWithImage` only works if the user is authenticated. It allows you to pin to a user's board from within your own app. 

If you update your pod to point to the latest commit then the invalid client_id should be fixed:
`pod 'PinterestSDK', :git => 'git@github.com:pinterest/ios-pdk.git', :commit => '9cc111bc728a7c6dd9f1c77df01b18191685b62a'`
