### ISSUE TITLE
Username is nil

### ISSUE THREAD

**Issue by deekshibellare** [pinterest/ios-pdk#103]
After the successful authentication, I can't access username from PDKUser. It is nil. My first name and second name is different from username. #

This issue is same as https://github.com/pinterest/ios-pdk/issues/73 and observed again.

**Comment by rahul-malik** [comment]
@deekshibellare - There appears to be a fix merged in April. Can you still reproduce this?

**Comment by deekshibellare** [comment]
It is fixed now. Thank you
