### ISSUE TITLE
Swift Cocoapod issue

### ISSUE THREAD

**Issue by samulegold2016** [pinterest/ios-pdk#105]
I had installed pinterest SDK in swift project by using cocoa pod.

use_frameworks!
target 'XXX' do
    pod 'PinterestSDK'
end

Then I had tried to import PDKClient class. But I am getting error. "No such module PDKClient"

Could you tell me solve way?
Thanks.

**Comment by jinthreek89** [comment]
It is problem of Xcode.
Please build project, then warning message will be disappear.

**Comment by rahul-malik** [comment]
@samulegold2016 - Please try @jinthreek89 fix and let us know if you are still encountering issues.
