### ISSUE TITLE
How can I send message to friend?

### ISSUE THREAD

**Issue by samulegold2016** [pinterest/ios-pdk#106]
I am trying to invite friends in Pinterest SDK. I got PDKUser array.
But I can't find method to send message to PDKUser.

How can I do? 
At least, can I get email address from PDKUser? 

Please help me.
Thanks.

**Comment by connor** [comment]
Hi @samulegold2016,

As you can see on our [API docs](https://developers.pinterest.com/docs/api/users/), this method isn't supported by our public API at this time. We also don't expose a user's email address in the API.
