### ISSUE TITLE
I need cancel Callback

### ISSUE THREAD

**Issue by jinthreek89** [pinterest/ios-pdk#107]
There is success and failure callback method.
But I need cancel callback method.

**Comment by rahul-malik** [comment]
@jinthreek89  - You don't actually need a cancellation callback so I'm closing this for now. The HTTP client uses AFNetworking which executes the failure callback when the request is cancelled. You should be able to detect a cancellation by inspecting the `code` property of the error object to see if it's equal to `NSURLErrorCancelled`. 

Here are the tests from AFNetworking that display this behavior:
https://github.com/AFNetworking/AFNetworking/blob/0e947a7ae6f6444ba42129ca5a054150c9725765/Tests/Tests/AFHTTPSessionManagerTests.m

Apple documentation on cancelling NSURLSessionTask objects and error objects:
https://developer.apple.com/reference/foundation/nsurlsessiontask/1411591-cancel?language=objc
