### ISSUE TITLE
Create Image with Url not working properly

### ISSUE THREAD

**Issue by hassanizhar** [pinterest/ios-pdk#11]
![screen shot 2015-10-13 at 4 06 05 pm](https://cloud.githubusercontent.com/assets/13674763/10453318/8d7a3802-71c4-11e5-9a09-fa8979de11e0.png)

**Comment by garrettmoon** [comment]
We don't officially support Swift for the SDK currently. However, we're happy to accept pull requests which fix issues related to Swift!

**Comment by hassanizhar** [comment]
I am trying it through a bridging file like other apis, they all are working fine.
