### ISSUE TITLE
Problems with keeping user logged in

### ISSUE THREAD

**Issue by nharbo** [pinterest/ios-pdk#116]
Hi there!
I'm using your ios SDK, and I cant figure out how to keep my users logged in. If i call the PDKClient.sharedInstance().authorized it always says false, when launching the app, even though I log in with the authenticateWithPermissions .. Its like the token isn't saved in the keychain - and i really cant fugure out why!
Anyone who can help with this issue, or have had similar problems?
Thanks :-)

**Comment by nharbo** [comment]
Anyone? Im getting desperate ;p Cant find anything about this anywhere..

**Comment by nharbo** [comment]
Guys! I really need this to work. Can it be true that your PDK doesn't support this?!

**Comment by erwinl** [comment]
@nharbo, If you previously authorized, then on the next session you can try to authenticate the user silently via `[[PDKClient sharedInstance] silentlyAuthenticatefromViewController:withSuccess:`

**Comment by rahul-malik** [comment]
@nharbo - @erwinl is correct in that you need to use a different API method to re-authenticate your logged in user. The information is kept within the keychain.

Please note that you will have to handle the failure callback in `silentlyAuthenticatefromViewController:withSuccess:andFailure` since that will be called if there are no credentials to use for authentication.

```objc
/**
 *  This method will use the cached oauth token and permission to populate PDKClient's oauthToken
 *  property. If there is no cached oauth token this method will call the failure block and do 
 *  nothing else (i.e., no app switching to authenticate). 
 *
 *  @param presentingViewController The ViewController the SafariViewController (if available) will present from if the Pinterest app is not installed. If nil, an attempt will be made to automatically determine the proper presenting view controller.
 *  @param successBlock called if the cached token can be used to authenticate
 *  @param failureBlock called if there is no cached token
 */
- (void)silentlyAuthenticatefromViewController:(UIViewController *)presentingViewController
                                   withSuccess:(PDKClientSuccess)successBlock
                                    andFailure:(PDKClientFailure)failureBlock;
```
