### ISSUE TITLE
-canOpenURL: failed for URL: "pinterestsdk.v1://oauth/?app_name=%appName&permissions=read_public&client_id=%clientId" - error: "(null)"

### ISSUE THREAD

**Issue by MajestikM** [pinterest/ios-pdk#117]
Hi,

I am getting the following errors while testing the app locally. The app isn't approved yet but I was under the impression that it would work with a developer account. I am using the latest version of the iOS SDK and building for iOS 9.3.

-canOpenURL: failed for URL: "pinterestsdk.v1://oauth/?app_name=%appName&permissions=read_public&client_id=%clientId" - error: "(null)"

**Comment by nharbo** [comment]
It should work without being approved :-) Did you return PDKClient.sharedInstance().handleCallbackURL(url) in AppDelegate's openURL-method?

**Comment by MajestikM** [comment]
I have this in myApp's AppDelegate:

```
    func application(application: UIApplication, handleOpenURL url: NSURL) -> Bool {
        print("application(application: UIApplication, handleOpenURL url: NSURL) -> Bool")
        return PDKClient.sharedInstance().handleCallbackURL(url)
    }
```

But I'm still getting the: "-canOpenURL: failed for URL: "pinterestsdk.v1://oauth/?app_name=%appName&permissions=read_public&client_id=%clientId" - error: "(null)""

**Comment by nharbo** [comment]
Ah! It looks like you forgot to add your app informations in the info.plist file - try and google search for Pinterest info.plist :)

**Comment by caraballoj** [comment]
I had a similar issue when running my app on the simulator. It works when running the app on my device.

**Comment by vinu123** [comment]
I have the Pinterest app so it ask for permissions and after that it shows a message in yellow saying "This URL can't be shown"

**Comment by eedawa** [comment]
I'm having the same exact problem as vinu123. Authentication opens on the Pinterest app, but after pressing "Okay", a yellow bubble appears from the bottom saying "This URL can't be shown" so I cannot get redirected by to my own app (which is also in an unapproved state).

**Comment by eedawa** [comment]
@vinu123 I took a look at this the other day and the problem was with my plist. Under the URL types -> URL schemes that you set, make sure you have your id set correctly here as pdk000000 <- the zeroes should be your id number.
