### ISSUE TITLE
Visit option not available while pin using PinterestSDK ios

### ISSUE THREAD

**Issue by djbalakrishnan** [pinterest/ios-pdk#119]
I have tried with 2.3 and latest version(PDKClient) of the PinterestSDK, I Pin it using ` [PDKPin pinWithImageURL:[NSURL URLWithString:[NSString stringWithFormat:@"%@",imageURL?:[NSNull null]]] link:[NSURL URLWithString:[NSString stringWithFormat:@"%@",sourceURL]]
                          suggestedBoardName:@"Test" note:@"Test Pin" withSuccess:^
                      {
                          NSLog(@"successfully pinned pin");
                      }
                                  andFailure:^(NSError *error)
                      {
                          NSLog(@"pin it failed Error:%@",error);

```
                  }];`
```

pin posted successfully , but visit option is missing in iOS alone. Android and Html it shows the visit button and it redirect to respective webpage of the client website

**Comment by jay-zhu** [comment]
Yes. I have a same issue #118  If you are using older version pinterest app, it will fine. I guess there's something wrong for the latest pinterest app.

**Comment by rahul-malik** [comment]
@djbalakrishnan @jay-zhu - Can you verify this is still occurring in the latest version of the Pinterest app (6.15)?

**Comment by jay-zhu** [comment]
@rahul-malik ,no, still cannot visit the link.

**Comment by djbalakrishnan** [comment]
@rahul-malik & @jay-zhu  , I have find out the issue, we are encoding share url and PDK again encode the same leads to the problem, now I have identified and corrected by remove encode in my side, it is working as expected now
