### ISSUE TITLE
ios9 did not call back when cancel authorized

### ISSUE THREAD

**Issue by heyuan110** [pinterest/ios-pdk#12]
the error message  when authorized.
![img_0015](https://cloud.githubusercontent.com/assets/769147/10455192/7493952c-71ec-11e5-95b2-9f0023492a18.JPG)

**Comment by rcancro** [comment]
What did your authorization URL look like? Looks like the error is around your app id.

**Comment by rcancro** [comment]
You will see this if we don't have your appId registered yet.
