### ISSUE TITLE
Pinterest applinks

### ISSUE THREAD

**Issue by amol-c** [pinterest/ios-pdk#126]
I am not sure if this is the right place to open an issue.

We have been trying to use applinks (http://applinks.org/documentation/) from Pinterest app to our app. It seems Pinterest app used to support it using Applinks, but it seems to be not working anymore.

We got it working for the Facebook and the Facebook app opens our app successfully instead of redirecting to the website.

Can someone from Pinterest help us out here? We have a lot of traffic from Pinterest and we would like them to forward to the app, instead of taking them to the browser.

Thanks for any help !

**Comment by rahul-malik** [comment]
@amol-c : Thanks for your report. The Pinterest application currently does not support forwarding to third-party applications using AppLinks. While this might change at some point in the future it is not currently planned and shouldn't be relied upon.

**Comment by amol-c** [comment]
@rahul-malik Thanks for the update.
