### ISSUE TITLE
Error with PDKPin

### ISSUE THREAD

**Issue by vsridharan6** [pinterest/ios-pdk#13]
Hi,

I am calling this api, and passing in the right values.

+ (void)pinWithImageURL:(NSURL *)imageURL
                   link:(NSURL *)sourceURL
     suggestedBoardName:(NSString *)suggestedBoardName
                   note:(NSString *)pinDescription
            withSuccess:(PDKUnauthPinCreationSuccess)pinSuccessBlock
             andFailure:(PDKUnauthPinCreationFailure)pinFailureBlock

I am getting error as shown in the screenshot.
https://www.dropbox.com/s/ebknzbrpgt2awzq/IMG_2155.PNG?dl=0

**Comment by vsridharan6** [comment]
(lldb) po params
{
    "app_name" = Gather;
    "client_id" = 4793241098596125683;
    description = test;
    "image_url" = "https://d1k9c6dzmnlqpr.cloudfront.net/profilemedia%3A1152921504606847871%3Apicture%3A13f40864692eb19bcf6741b1";
    "source_url" = "http://my.gather.to/1OAhr3F";
    "suggested_board_name" = " ";
}

(lldb) po pinitURL
pinterestsdk.v1://pinit/?client_id=4793241098596125683&source_url=http%3A%2F%2Fmy.gather.to%2F1OAhr3F&app_name=Gather&image_url=https%3A%2F%2Fd1k9c6dzmnlqpr.cloudfront.net%2Fprofilemedia%253A1152921504606847871%253Apicture%253A13f40864692eb19bcf6741b1&suggested_board_name=%20&description=test

**Comment by vsridharan6** [comment]
Extra info here:

    (lldb) po params
    {
    "app_name" = Gather;
    "client_id" = 4793241098596125683;
    description = test;
    "image_url" = "https://d1k9c6dzmnlqpr.cloudfront.net/profilemedia%3A1152921504606849284%3Apicture%3A140a69616b66171e00a967e1";
    "source_url" = "http://my.gather.to/1Mrg7M4";
    "suggested_board_name" = test;
    }

    (lldb) po pinitURL
    pinterestsdk.v1://pinit/?client_id=4793241098596125683&source_url=http%3A%2F%2Fmy.gather.to%2F1Mrg7M4&app_name=Gather&image_url=https%3A%2F%2Fd1k9c6dzmnlqpr.cloudfront.net%2Fprofilemedia%253A1152921504606849284%253Apicture%253A140a69616b66171e00a967e1&suggested_board_name=test&description=test

**Comment by scohen** [comment]
@rcancro ^^

**Comment by vsridharan6** [comment]
Gentlemen, any updates on this issue? :)  

Thanks.

**Comment by scohen** [comment]
If you want to be unblocked, don't pass the client_id.

**Comment by vsridharan6** [comment]
You are right. 
Awesome. Thanks for the quick reply.

**Comment by scohen** [comment]
No problem. Ricky and I are working on getting this fixed as well.

**Comment by vsridharan6** [comment]
Thanks Steve. I'll get the updated sdk when it's ready. For now, I will use remove the client_id :+1:

**Comment by rcancro** [comment]
Update to the latest commit and you should be able to pass your appId:

`pod 'PinterestSDK', :git => 'git@github.com:pinterest/ios-pdk.git', :commit => '9cc111bc728a7c6dd9f1c77df01b18191685b62a'`

**Comment by vsridharan6** [comment]
:+1:
