### ISSUE TITLE
Api to fetch new boards - Need a fix

### ISSUE THREAD

**Issue by vsridharan6** [pinterest/ios-pdk#14]
1. Create a board with no image in it. 
2. Call the api to get all the boards.

[[PDKClient sharedInstance] getAuthenticatedUserBoardsWithFields:[NSSet setWithObjects:@"id", @"name", @"url", @"description", @"image[medium]", nil] ....

3. When you ask for image, the client either expects NO image field set, or at least some sort of place holder. Not this.
description = "test 3";
id = 432064226690179447;
image = {
medium = {
height = 150;
url = "<null>";
width = 200;
};
};

name = "Testing 3";

That value "<null>". No. This has to be fixed. 

Right now I can add some cases to handle this, but this is passed as a string value.

**Comment by vsridharan6** [comment]
Ok github seems to have an issue - but the value in the response is url="<null">

**Comment by rcancro** [comment]
I'm confused -- if the board has no image, why is the image being null wrong?

**Comment by vsridharan6** [comment]
This is because its not the right `json` format. It's not right to insert "< null >" in the field if it's not available.  Different clients will have to deal with this differently.

For example, in  my case, 

        if (imageURL && ![imageURL isKindOfClass:[NSNull class]]) {
       // start processing this data.
       }


In this example, imageURL is set to < null >. But I have to explicitly add this second check if its a NSNull class. Clients do not need to handle this check if its a [NSNull class]. The assumption is that server follows right json format, and whatever it gives us is legit. 

What would be right is - give me a placeholder image, or don't return any id for an image, or width, and height for an image that does not exist. 

Do you use `Go` for backend?

**Comment by garrettmoon** [comment]
You're right, it would be convenient if the JSON returned parsed out the NSNulls and turned them into nils. Happy to accept a pull request.

**Comment by vsridharan6** [comment]
[Hi Garrett, I do not believe this is an enhancement - but it is up to you. This is a just a simple bug fix that the team responsible for your server-side code needs to spend a few minutes on. With respect to me sending a PR -> Patching this on the sdk side is a hack.]

I don't think there is git access to your server side code. We have faced issues like this before - basically forward this to your backend team, and give them the proper json documentation - they will know what the problem is.

**Comment by scohen** [comment]
Is the problem that you're seeing:
```json
{
"image": {
"60x60": {
"url": null,
"width": 60,
"height": 60
}
}
```
or that you're seeing
```

**Comment by vsridharan6** [comment]
<img width="368" alt="screen shot 2015-10-14 at 3 58 40 pm" src="https://cloud.githubusercontent.com/assets/2198154/10500368/88a807b4-728c-11e5-985a-7d3c76554aec.png">

**Comment by vsridharan6** [comment]
I pasted the image as git is not rendering it right - what I am seeing on my end.
board id, etc, check original description of this issue on top.

**Comment by scohen** [comment]
A couple of things. If you want to paste in code, use fenced code blocks, which start with three backticks (`) and then the language you're using (json in this case). 

Secondly, that board doesn't exist. If you could give me a valid board id, that's be very helpful.

Third, that code you pasted in doesn't look like it's JSON at all. Are you sure that's exactly the string that's coming from the API? 

Our backend is python, it would be very challenging for us to emit "<null>" as a value.

**Comment by rcancro** [comment]
The "JSON" that you are seeing is the result of ASNetworking parsing raw JSON into an NSDictionary (presumably using the built-in JSON parser). The NSDictionary CANNOT have nil as an object, so the OS puts in an NSNull object. It is your responsibility to handle these NSNulls.

**Comment by vsridharan6** [comment]
Pasting code. Thank you :+1:  :)

That board might have gotten deleted. Its a simple test - Just create a board with no image in it, and call the board list api. 

       (lldb) po json
     {
        data =     (
                  {
              description = "Gather puts you in touch with interesting people you pass by!";
              id = 414331303157421872;
              image =             {
                medium =                 {
                    height = 150;
                    url = "<null>";
                    width = 200;
                };
              };
              name = test;
             url = "https://www.pinterest.com/Vensriz/test/";
            },
                {
            description = "";
            id = 414331303157352389;
            image =             {
                medium =                 {
                    height = 150;
                    url = "http://media-cache-ec0.pinimg.com/200x150/ca/ce/22/cace22d37c18ce90a90d322fbce9ae72.jpg";
                    width = 200;
                };
            };
            name = Healthy;
            url = "https://www.pinterest.com/Vensriz/healthy/";
        },
                {
            description = "";
            id = 414331303157287399;
            image =             {
                medium =                 {
                    height = 150;
                    url = "http://media-cache-ec0.pinimg.com/200x150/04/f0/0a/04f00a058ed6a4d3b367c20f5513a51a.jpg";
                    width = 200;
                };
            };
            name = Cocktails;
            url = "https://www.pinterest.com/Vensriz/cocktails/";
        },
                {
            description = "Gather puts you in touch with interesting people you pass by!";
            id = 414331303157421864;
            image =             {
                medium =                 {
                    height = 150;
                    url = "<null>";
                    width = 200;
                };
            };
            name = hi;
            url = "https://www.pinterest.com/Vensriz/hi/";
        },
                {
            description = "";
            id = 414331303157337145;
            image =             {
                medium =                 {
                    height = 150;
                    url = "http://media-cache-ec0.pinimg.com/200x150/56/12/20/56122039a7c8d7e03e7564f7e20f709f.jpg";
                    width = 200;
                };
            };
            name = Fashion;
            url = "https://www.pinterest.com/Vensriz/fashion/";
        },
                {
            description = "";
            id = 414331303157272885;
            image =             {
                medium =                 {
                    height = 150;
                    url = "http://media-cache-ak0.pinimg.com/200x150/60/df/fb/60dffba054b34cd93bb0f6b6b75fbda5.jpg";
                    width = 200;
                };
            };
            name = Motorcycles;
            url = "https://www.pinterest.com/Vensriz/motorcycles/";
        }
    );
}

**Comment by scohen** [comment]
Are you saying that what you'd like to see instead is:
```json
{
  name: "Motorcycles"
  image: null
  ...
}
```
?

**Comment by vsridharan6** [comment]
The image key should not even be there. Clients who consume the json will know that image is not there.

There are better ways as well. Like if you check the Facebook SDK (for example), if images are not present, you won't see them in the response. Likewise, for profile images, they follow a practice where they will always return a placeholder image in the response (even if the profile image is not there).

Clients who consume the api who see images present will start reading the values - in your case - only to find out its null.

**Comment by scohen** [comment]
I don't think I agree, you asked for the key, shouldn't it be there?

**Comment by vsridharan6** [comment]
It's up to you guys how you want to design you apis. :)  I am just a client who has feedback on something very simple which can improve integration experience. Eventually everyone who calls this api with empty board will crash their apps and then learn they need to handle this case. It's just extra processing on client side for no reason. It's up to you.
