### ISSUE TITLE
Problem with sharing

### ISSUE THREAD

**Issue by amyhametov** [pinterest/ios-pdk#142]
New version of Pinterest iOS app works wrong with current ios-pdk.
It seems like, when we use PDKPin for sharing in Pinterest, there are redundant url encoding usage for some parameters in method pinWithImageURL.
May be you should fix Pinterest app?

**Comment by stevel6868** [comment]
I also see this problem, and confirm that amyhametov's workaround addresses the issue for now.

**Comment by timonus** [comment]
We recently made a change to how the app handles URL encoding which might be the source of this. Will investigate and get back to you.

**Comment by stevel6868** [comment]
Thanks Tim.  While you are at it, can you confirm that redirection back to the calling app still works, after calling PDKPin pinWithImageURL.  It no longer works for me, and I can't find anything wrong on my side of things.   I contacted support a couple of weeks back.

**Comment by timonus** [comment]
Alright, I've made an update to Pinterest's iOS app that should fix this. The fix will go out with Pinterest iOS 6.30, slated to launch July 17th.

**Comment by stevel6868** [comment]
Thanks Tim,

Will your update break apps that use the fix that removes the URL encoding from PDKPin.h?

Steve

**Comment by timonus** [comment]
I made it so the app decodes the parameters the PDK passes to it one additional time, which might not cause breakage for some URLs but in general won't be safe with the fix you applied. Best to stick with the default PDK once the change to Pinterest has rolled out.

**Comment by PranaviOSGit** [comment]
I found the same issue with pintrestSDK. i have fixed with this method.

-  remove the _PDK_urlEncodedString method from  image_url, source_url, description, suggested_board_name

NSDictionary *params = @{@"app_id" : [PDKClient sharedInstance].appId,
                             @"image_url" : [imageURL absoluteString],
                             @"source_url" : [sourceURL absoluteString],
                             @"app_name" : [appName _PDK_urlEncodedString],
                             @"suggested_board_name" : suggestedBoardName,
                             @"description" : pinDescription,
                             };
