### ISSUE TITLE
Image sharing on pinterest throws error invalid parameters

### ISSUE THREAD

**Issue by djohn17** [pinterest/ios-pdk#144]
Its been noticed that I am unable to share image url from my iOS app on pinterest when pinterest app is installed on my device. It throws below error all the time:
![img_2677](https://user-images.githubusercontent.com/19919009/27845939-8d1f1986-6187-11e7-9930-c239c424ee7e.PNG)

Below is the code I am using 

![code](https://user-images.githubusercontent.com/19919009/27845963-be1835ae-6187-11e7-98a7-f41ddfc2249b.png)

But the same image url gets shared properly on pinterest if the pinterest app isn't installed and we use web browser.  Can you please review this issue?

**Comment by timonus** [comment]
This will be fixed in an update to the Pinterest app, more details here https://github.com/pinterest/ios-pdk/issues/142
