### ISSUE TITLE
Can not use SDK

### ISSUE THREAD

**Issue by MaximBoyarskiy** [pinterest/ios-pdk#145]
SDK works perfectly. However, I have submitted my app on review and it is in pending status for ages!
https://developers.pinterest.com/apps/4893585622819684418/ - my app

Support form https://developers.pinterest.com/support/contact/ is broken for years. I just want to bring your attention here. Thank you in advance!

**Comment by arunranga** [comment]
@MaximBoyarskiy we just approved your app. We also issued a caveat about image usage, and linked to our policies on this.

**Comment by MaximBoyarskiy** [comment]
Arun thank you! I have been waiting for it! I didn't find any link mentions about image usage. As I described in app info: app gives user ability to use their own pinterest boards as a template of images collection in app (to do app with images instead text). So user uses only his own boards.
