### ISSUE TITLE
SDK is crashing with response data.  Numbers changed to strings for appId, etc?

### ISSUE THREAD

**Issue by scottcarter** [pinterest/ios-pdk#159]
Our app just started crashing in the Pinterest SDK.  We are using the latest release: 1.0.2

It appears that the response data format for certain fields such as appId, userId may have changed?

Our app initiates a call to 

```objective-c
[[PDKClient sharedInstance] silentlyAuthenticatefromViewController:nil withSuccess:nil andFailure:nil]
```

This eventually results in a call to the following method in PDKClient.m

```objective-c
- (BOOL)verifyTokenDetails:(NSDictionary *)dictionary

```

The following comparison crashes since appId is a string, not a number:

```objective-c
[appId isEqualToNumber:cachedAppId]
```
Example value of appId and cachedAppId (which are identical): @"4145005065503282978"   (value changed slightly to protect identity).

Exception message: 
    *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString isEqualToNumber:]: unrecognized selector sent to instance 0x17025fb90'

**Comment by morpholio** [comment]
Same here! The crashing began on the 24th of August and has continued since. Huge problem...

**Comment by gesabo** [comment]
Same

**Comment by jmejiaa** [comment]
+1

**Comment by arunranga** [comment]
Hi folks (Cc @scottcarter, @morpholio, @gesabo , @cjiao , @jmejiaa ):

We fixed this issue; the patch should roll-out with our latest deploy this morning. 

What had happened is that a patch to the API system was correcting for very large integers (see `MAX_SAFE_INTEGER` [discussion](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)). These were being cast to strings. Many appIDs are large ints.

While we're sorry iOS apps had crashes, Pinterest considers our SDKs to be frozen at present time. Going forward, it's prudent to use the RESTFul endpoints directly.

HTH,

-- A*

**Comment by jmejiaa** [comment]
Thanks @arunranga - would be helpful to update this repo and point out that the sdk is no longer worked on.

**Comment by scottcarter** [comment]
Hi @arunranga - Just to clarify:  Are you patching the SDK, or making a change to the back-end to fix?  I.e. will our apps need to be updated after your fix?

**Comment by arunranga** [comment]
@scottcarter technically, things should work as they did before 08.23, without requiring changes on your end. Changes we made are to backend.

**Comment by scottcarter** [comment]
I confirmed that our app is now working again properly.

Thanks!
