### ISSUE TITLE
-canOpenURL: failed for URL: "pinterestsdk.v1

### ISSUE THREAD

**Issue by andreitr** [pinterest/ios-pdk#16]
Hey there, I am getting the following errors while testing the app locally. The app isn't approved yet but I was under the impression that it would work with a developer account. I am using the latest version of the iOS SDK and building for iOS 9. 

    APP NAME[35910:7039910] -canOpenURL: failed for URL: "pinterestsdk.v1://oauth/?

    APP NAME[35910:7039910] -canOpenURL: failed for URL: "pinterestsdk.v1://oauth/?client_id=APP_ID&permissions=read_public%2Cwrite_public%2Cread_private%2Cwrite_private%2Cread_relationships%2Cwrite_relationships&app_name=APP%20NAME" - error: "This app is not allowed to query for scheme pinterestsdk.v1"

**Comment by rcancro** [comment]
You need to set up your app's plist to allow you to call out to the pinterestsdk.v1 URL.

Add this to your plist:
![url](https://cloud.githubusercontent.com/assets/285809/10553562/b4b62586-7410-11e5-9e05-9adb96387827.png)

**Comment by andreitr** [comment]
@rcancro  thanks! 

I've updated 'LSApplicationQueriesSchemes' to 'pinterestsdk.v1' but still getting the following error:

    2015-10-16 15:24:24.394 Off The Easel[40602:7326793] -canOpenURL: failed for URL: "pinterestsdk.v1://oauth/?client_id=APP_ID&permissions=read_public%2Cwrite_public%2Cread_private%2Cwrite_private%2Cread_relationships%2Cwrite_relationships&app_name=Off%20The%20Easel" - error: "(null)"

p.s. the documentation on this page https://developers.pinterest.com/docs/sdks/ios/ suggests that 'LSApplicationQueriesSchemes' should be set to 'pinterest'? Is it outdated?

**Comment by BigDipper0210** [comment]
I updated pod. so PinterestSDK is updated to 1.0.2.
When run the app, I got same error.
How can i solve this problems?

Thanks
