### ISSUE TITLE
Can't install PinterestSDK pod after updating AFNetworking pod

### ISSUE THREAD

**Issue by standlr** [pinterest/ios-pdk#160]
I am having trouble installing PinterestSDK after updating AFNetworking pod to it's latest version (4.0.1). Seems like PinterestSDK works only with AFNetworking version prior to 3.0.

![10_45_40__06_01_2020](https://user-images.githubusercontent.com/21988099/83371461-19991800-a3f5-11ea-9298-46d83cf1176d.jpg)

**Comment by dulifu** [comment]
I have the same problem, have you solved it?

**Comment by standlr** [comment]
sorry

**Comment by dulifu** [comment]
> sorry

你好，请问你这边有解决问题了吗 不更新AFN，提交app store审核会报一个UIWebView的警告，而且给出了最终期限是今年12月份

**Comment by dulifu** [comment]
你好，请问你这边有解决问题了吗？ 不更新AFN，提交app store审核会报一个UIWebView的警告，而且给出了最终期限是今年12月份, 有什么解决方案告知下，非常感谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liqiang li"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 下午3:51
收件人:&nbsp;"pinterest/ios-pdk"<ios-pdk@noreply.github.com&gt;;
抄送:&nbsp;"下线的时候"<1070192262@qq.com&gt;;"Manual"<manual@noreply.github.com&gt;;
主题:&nbsp;Re: [pinterest/ios-pdk] Can't install PinterestSDK pod after updating AFNetworking pod (#160)





 
sorry

**Comment by standlr** [comment]
他们已经弃用了这个SDK。 建议直接把他们的源文件 导入到项目中。
然后引入AFNetworking,SAMKeychain 三方库文件。
把他们报错的地方处理掉就可以了,改动的地方很小。

**Comment by dulifu** [comment]
好的 我尝试下，谢谢啦



发自我的iPhone


------------------ Original ------------------
