### ISSUE TITLE
failed for URL: "pinterestsdk.v1...."

### ISSUE THREAD

**Issue by antrix1989** [pinterest/ios-pdk#20]
I had the following error on iOS 9:
```
2015-10-21 12:30:35.269 AppName[913:453759] -canOpenURL: failed for URL: "pinterestsdk.v1://oauth/?client_id=4797042421225493369&permissions=read_public&app_name=AppName" - error: "This app is not allowed to query for scheme pinterestsdk.v1"
```

In order to fix it, developer should add to LSApplicationQueriesSchemes key in Info.pllist item "pinterestsdk.v1".

![uzhlfz7mwj_knwlrkg03hks8nqskvxrfk8c3pdcprxs](https://cloud.githubusercontent.com/assets/1989385/10648184/d87c9f9c-77f1-11e5-98fe-0b7d399c93bf.png)

[Stackoverflow](http://stackoverflow.com/questions/30987986/ios-9-not-opening-instagram-app-with-url-scheme)

It would be great if you add this info to readime file.

**Comment by andreitr** [comment]
+1

**Comment by rcancro** [comment]
This is mentioned in the docs (though it is at the bottom):
https://developers.pinterest.com/docs/sdks/ios/

**Comment by LucyNguyen** [comment]
This saves my day, thank you so much, Antrix1989.

**Comment by virusss8** [comment]
Thanks a lot, you saved me a lot of time!

**Comment by agroGandhi** [comment]
Thanks
