### ISSUE TITLE
handleOpenURL is deprecated in iOS 9

### ISSUE THREAD

**Issue by antrix1989** [pinterest/ios-pdk#21]
This method is deprecated in iOS 9.

[Documentation](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/index.html#//apple_ref/occ/intfm/UIApplicationDelegate/application:handleOpenURL:)

Moreover, If the delegate also implements the application:openURL:sourceApplication:annotation: method, that method is called instead of this one.

I think the proper way to handle callback urls is to implement
```
application:openURL:sourceApplication:annotation: 
```

it would be great if you mention this in readme file.

**Comment by rcancro** [comment]
I'd happily review/accept a pull request with these changes.
