### ISSUE TITLE
Request failed: not found (404)

### ISSUE THREAD

**Issue by hassanizhar** [pinterest/ios-pdk#26]
Getting the following error when creating pin:

Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: not found (404)" UserInfo=0x1742e1880 {com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x17003a7a0> { URL: https://api.pinterest.com/v1/pins/ } { status code: 404, headers {
    "Accept-Ranges" = bytes;
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = private;
    Connection = close;
    "Content-Length" = 64;
    "Content-Type" = "application/json";
    Date = "Thu, 29 Oct 2015 10:30:29 GMT";
    "Pinterest-Generated-By" = None;
    "Pinterest-Version" = f8e949f;
    Server = nginx;
    "X-Content-Type-Options" = nosniff;
    "X-Pinterest-RID" = 292308685227;
    "X-Ratelimit-Limit" = 200;
    "X-Ratelimit-Remaining" = 196;
    "X-Varnish" = 985568870;
} }, NSErrorFailingURLKey=https://api.pinterest.com/v1/pins/, com.alamofire.serialization.response.error.data=<7b226d65 73736167 65223a20 22426f61 7264206e 6f742066 6f756e64 2e222c20 22747970 65223a20 22617069 222c2022 70617261 6d223a20 22626f61 7264227d>, NSLocalizedDescription=Request failed: not found (404)}

**Comment by rcancro** [comment]
I was able to create a pin using the sample app in the SDK. Does that work for you? 
Authenticate, then choose "view boards". There you can add a new pin to a board.

Also, make sure your Podfile is pointing to the latest commit of the SDK.

**Comment by hassanizhar** [comment]
I tried but that also didn't work.
Code:

        PDKClient.sharedInstance().authenticateWithPermissions([PDKClientReadPublicPermissions, PDKClientWritePublicPermissions, PDKClientReadPrivatePermissions, PDKClientWritePrivatePermissions, PDKClientReadRelationshipsPermissions, PDKClientWriteRelationshipsPermissions], withSuccess: { (object: PDKResponseObject!) -> Void in
            print("success")
            PDKClient.sharedInstance().getBoardWithIdentifier("Test", fields: NSSet() as Set<NSObject>, withSuccess: { (object: PDKResponseObject!) -> Void in
                print("success")
                }, andFailure: { (error: NSError!) -> Void in
                    print(error.description)
            })
            }) { (error:NSError!) -> Void in
                print(error.description)
        }

Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: bad request (400)" UserInfo=0x1740e5c80 {com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x17022b600> { URL: https://api.pinterest.com/v1/boards/Moda/?access_token=AYfpudrRneBcMS02ePbeScXQaVkyFBGhlxnzp6pCl-eA-6AIiQAAAAA&fields= } { status code: 400, headers {
    "Accept-Ranges" = bytes;
    "Cache-Control" = private;
    Connection = "keep-alive";
    "Content-Length" = 173;
    "Content-Type" = "application/json";
    Date = "Fri, 30 Oct 2015 05:54:58 GMT";
    "Pinterest-Generated-By" = "coreapp-devplatform-devapi-189";
    "Pinterest-Version" = f8e949f;
    Server = nginx;
    "X-Content-Type-Options" = nosniff;
    "X-Pinterest-RID" = 411810384607;
    "X-Varnish" = 2409671497;
} }, NSErrorFailingURLKey=https://api.pinterest.com/v1/boards/Moda/?access_token=AYfpudrRneBcMS02ePbeScXQaVkyFBGhlxnzp6pCl-eA-6AIiQAAAAA&fields=, com.alamofire.serialization.response.error.data=<7b227374 61747573 223a2022 6661696c 75726522 2c202263 6f646522 3a20312c 2022686f 7374223a 2022636f 72656170 702d6465 76706c61 74666f72 6d2d6465 76617069 2d313839 222c2022 67656e65 72617465 645f6174 223a2022 4672692c 20333020 4f637420 32303135 2030353a 35343a35 38202b30 30303022 2c20226d 65737361 6765223a 2022496e 76616c69 64207061 72616d65 74657273 2e222c20 22646174 61223a20 6e756c6c 7d>, NSLocalizedDescription=Request failed: bad request (400)}

**Comment by hassanizhar** [comment]
I just want to share a post on Pinterest, I don't know why guys made it so complicated to just share a post. It should be as easy as Facebook and Twitter i.e they show a share dialog.

**Comment by hassanizhar** [comment]
Done but too complicated, would've been made much easier like Facebook and Twitter.

**Comment by fikeminkel** [comment]
@hassanizhar: There is an undocumented way to do this much more simply using the SDK. From the example app's `pinItButtonTapped` function:
```
[PDKPin pinWithImageURL:[NSURL URLWithString:@"https://about.pinterest.com/sites/about/files/logo.jpg"]
                       link:[NSURL URLWithString:@"https://www.pinterest.com"]
         suggestedBoardName:@"Tooty McFruity"
                       note:@"The Pinterest Logo"
                withSuccess:^
    {
        weakSelf.resultLabel.text = [NSString stringWithFormat:@"successfully pinned pin"];
    }
                 andFailure:^(NSError *error)
    {
        weakSelf.resultLabel.text = @"pin it failed";
}];
```

This will launch the Pinterest app with a board chooser dialog and does not require to you authenticate the user yourself against the SDK. The problem with this approach is that this only works if the user already has the Pinterest app installed on their device. I've added a workaround in my app to deal with this scenario:
```
// This should really be a part of the SDK
NSString * const PinterestSDKUrl = @"pinterestsdk.v1://pinit/";
-(BOOL)canPinWithSDK {
    return [[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:PinterestSDKUrl]];
}
NSString * const PinterestAppStoreUrl = @"https://itunes.apple.com/us/app/pinterest/id429047995";

-(void)performPinterestShareWithImageURL:(NSURL *)imageURL sourceURL:(NSURL *)sourceURL description:(NSString *)description
{
    if ([self canPinWithSDK]) {
        [PDKPin pinWithImageURL:imageURL link:sourceURL suggestedBoardName:@"Board Name" note:description withSuccess:^{
        } andFailure:^(NSError *error) {
        }];
    } else {
        // Point App Store to Pinterest App like the old SDK used to do
        [[UIApplication sharedApplication] openURL:[NSURL URLWithString:PinterestAppStoreUrl]];
    }
}
```

Also make sure that you're overriding both `handleOpenURL` and `openURL` in your AppDelegate calling `[[PDKClient sharedInstance] handleCallbackURL:url]` to make sure the SDK can switch to the Pinterest app and back to yours properly.

**Comment by rcancro** [comment]
Oh wow, you are right! We didn't mention the unauth method in the documentation. I'll make sure that gets updated. Sorry about that!!!
