### ISSUE TITLE
`oauthToken` returns `nil` after app was killed

### ISSUE THREAD

**Issue by mkalmes** [pinterest/ios-pdk#27]
I've successfully called `authenticateWithPermissions:withSuccess:andFailure:` and I'm receiving a value from `oauthToken`. When I kill my app and call `oauthToken` again, I'll receive `nil`.

When I add the following line to `[PDKClient -initWithBaseURL]`, `oauthToken` behaves as expected.

```
_oauthToken = [SSKeychain passwordForService:PDKPinterestSDK account:PDKPinterestSDKUsername];
```

Is this the right approach or should I persist the token in my app?

**Comment by rcancro** [comment]
Before you make an authenticated SDK call, you should call:
```
- (void)authenticateWithPermissions:(NSArray *)permissions
                        withSuccess:(PDKClientSuccess)successBlock
                         andFailure:(PDKClientFailure)failureBlock
```
If you have authenticated in a previous session the cached oauthToken will be "inspected" to make sure that it is still valid. If it is then `oauthToken` in `PDKClient` will be populated. If the token is no longer valid, the user will be app-switched to Pinterest and asked to reauthenticate.

A good idea would be to create a silent authenticate that will inspect the cached token and populate `oauthToken` if it is valid. If it is not valid nothing would happen. I don't have time to do that right now, but would be happy to look at a PR :)

**Comment by rcancro** [comment]
Actually, I just added it. 
https://github.com/pinterest/ios-pdk/pull/29
Should be in master now.

**Comment by mkalmes** [comment]
Awesome! Thanks! :+1:

**Comment by parkerdonat** [comment]
I have a similar issue as MKalmes but my app crashes every time I use the createPinWithImage method.  Each time is says, "self.oauthToken cannot be nil". I have incorporated the silent authentication and even added the latest commit in my podfile. Any ideas?

**Comment by rcancro** [comment]
Are you authenticating before trying to call createPinWithImage? If you want to pin without authenticating, look in PDKPin for the create pin class method. It doesn't require authentication.
