### ISSUE TITLE
Pinning with createPinWithImage method but returns OauthToken as Nil 

### ISSUE THREAD

**Issue by parkerdonat** [pinterest/ios-pdk#31]
I feel like I am so close to being able to pin an image but it hasn't worked for me yet. I looked at a similar issue however mine just does't want to pin. I'm hoping someone could help me out. So my app crashes every time I use the createPinWithImage method. It breaks saying, "self.oauthToken cannot be nil".

Here is my output message: 

*** Assertion failure in -[PDKClient multipartFormRequestWithMethod:path:parameters:constructingBodyWithBlock:], /Code/Projects/PhotoTower/Pods/PinterestSDK/Pod/Classes/PDKClient.m:427

I've uninstalled and then reinstalled cocoapods thinking that would fix it: http://www.jmeveryday.com/how-to-remove-cocoapods-from-a-project/ 

But nothing seems to work. I have incorporated silent authentication and even added the latest commit in my podfile. I used the most current "example app" as a reference to see if I missed anything and I just can't figure it out.  I'm up to date on the newest versions of cocoapods (0.39.0), xcode (Version 7.1), and iOS (9.1). 

Any ideas? Any help would be very appreciated. Thanks.

**Comment by hassanizhar** [comment]
Are you calling authenticateWithPermissions before createPinWithImage?

**Comment by rcancro** [comment]
If all you want to do is pin something (i.e., not pull in a user's info, boards, pins, etc) then you can use this method in `PDKPin`:
```
/**
 *  Creates a pin without obtaining an oauth token
 *
 *  @param imageURL           The URL of the image to pin
 *  @param sourceURL          The URL to the source of the pin
 *  @param suggestedBoardName A suggested name of a board to pin to
 *  @param pinDescription     The description of the pin
 *  @param successBlock Called when the API call succeeds
 *  @param failureBlock Called when the API call fails
 */
+ (void)pinWithImageURL:(NSURL *)imageURL
                   link:(NSURL *)sourceURL
     suggestedBoardName:(NSString *)suggestedBoardName
                   note:(NSString *)pinDescription
            withSuccess:(PDKUnauthPinCreationSuccess)pinSuccessBlock
             andFailure:(PDKUnauthPinCreationFailure)pinFailureBlock;
```

It does not require authentication, but will redirect you to the Pinterest app to create the pin.

The downside is that the redirect back to your app was broken in iOS9 for Pinterest 5.5 and below. 5.6 is now out and it fixes the issue.

**Comment by parkerdonat** [comment]
Thank you for your quick responses. 

@hassanizhar Yes, I am calling authenticateWithPermissions BEFORE createPinWithImage. I am authenticating before I pin each time. Since the new silent authentication was available. Is that okay to do? Does the creatPintWithImage work for you? Should I use pinWithImageURL instead?

@rcancro you are right. All I need to do is pin an image. I was first using pinWithImageURL but had some issues with Amazon's server (S3) so I was leaning towards using createPinWithImage. So if I could get createPinWithImage working, that's what I would prefer. But if it's not going to work (or if you suggest otherwise), I can go back to tinkering with S3. Let me know what you think. And just to clarify, the redirect for pinWithImageURL is working in iOS9? Hope to hear from you soon. Thanks!

**Comment by rcancro** [comment]
Silent authentication doesn't do anything if you don't have stored credentials from a previous non-silent authentication.  The idea is that it allows you to check the validity of a stored oauth token without doing an app switch to reauthorize if the token has expired.

`pinWithImageURL` does not require authentication. It relies either on the user having the Pinterest app installed and switching to the app to pin or the user logging in to their Pinterest account via Safari to pin.

`createPinWithImage` only works after authentication. Once you authenticate (which will require an app switch) you can pin without leaving your app. You can provide whatever UI you want (or none at all).

As of Pinterest 5.6 the redirects for both cases should work. The authentication redirect worked in 5.5 and below as well.

If all you need to do is pin (i.e., you aren't grabbing a user's boards and displaying them) I'd recommend going with the unauthenticate choice. If you want a richer, customized experience, then go with the authenticated version.

**Comment by parkerdonat** [comment]
@rcancro thanks for the quick clarification. It sounds like I will go back to using pinWithImageURL then. One question that you made me think of just now, both method options allow for choosing which board the user wants to pin? Is that correct?

**Comment by rcancro** [comment]
In the authenticated version, you supply the board id that you want to pin to. There is no "free" UI that allows the user to select a board. You would need to get the ID from an authenticated call to get all of the user's boards (which you could display in a tableView in your own app, or you could do silently).

In the unauthenticated version you don't know who the user is, so you don't know the name of any of the user's boards. The most you can provide is a "suggested" board name. But, the user will be redirected to the Pinterest app where they are logged in and already authenticated. They will then get the same pin-it flow that we use in the Pinterest app that allows the user to pick the board to pin to.

Hope that answers your questions.

**Comment by parkerdonat** [comment]
This is great. Makes much more sense. Thank you. I'll work on the unauthenticated version.
