### ISSUE TITLE
After Successful Pin, Pinterest can not redirect to my (Requested) App

### ISSUE THREAD

**Issue by kayasiri** [pinterest/ios-pdk#32]
Hi,

I have integrated iOS PDK in my app (by following your documentation) and trying to Pin an image by using [PDKPin pinWithImageURL: ]. When I click on PinIt button in my app, PDK behaves as mentioned below.

**Case 1 : If Pinterest App Not Installed in My Device** 
PinterestSDK will authenticate user through Safari browser & even I provide valid credentials it's displaying **authentication failed** and also getting below error in my console. But Image has been Pinned in my Pinterest board. May I know why it's going to *FailureBlock* & returns like that? 

<img width="1132" alt="screen shot 2015-11-04 at 10 00 21 pm" src="https://cloud.githubusercontent.com/assets/1552756/10945580/1a067516-8344-11e5-8dc4-66217df0348e.png">

**Case 2 : If Pinterest App Already Installed in My Device** 
PinterestSDK will authenticate user via Pinterest app & in this case also even I provide valid credentials it's displaying **authentication failed** and **I am not getting above error here**. But Image has been Pinned in my Pinterest board. May I know why it's going to *FailureBlock* & returns like that? 

In both of above 2 cases, after image has been Pinned to my selected board, the request not came back to my app (from which we have requested) and but it's displaying success message.

I have followed your documentation with out fail anything.

So please help me on this issue and looking forward for your response.

Thanks,
Kayasiri.

**Comment by rcancro** [comment]
What version of the pod are you using? This sounds like it could be an issue we fixed recently. Make sure to point your pod to the latest commit.

**Comment by kayasiri** [comment]
@rcancro 

Hi Ricky,

I am not using any pod in this project and I recently downloaded (on Nov 02nd 2015) your pdk again from Github and I have added all dependency & required classes / files to my project and there is no any build errors. I thought the downloaded pdk may contains your latest commit also. I checked my system and pod version is 0.39.0. Is it mandatory the use of pod in order to integrate your iOS PDK in my project?

As you said in ticket #10, your latest commit (pod 'PinterestSDK', :git => 'git@github.com:pinterest/ios-pdk.git', :commit => '9cc111bc728a7c6dd9f1c77df01b18191685b62a')  will resolve only *invalid client_id* issue. 

My doubt is, why I am getting this error **-canOpenURL: failed for URL: "pinterestsdk.v1://oauth/?app_name=Pinterest&permissions=read_public%2Cwrite_public%2Cread_private%2Cwrite_private%2Cread_relationships%2Cwrite_relationships&client_id=4792222935410545828" - error: "(null)"** If I am not having Pinterest app on my device and why it's not came if I have Pinterest app on my device. I think it's not mandatory all devices should have Pinterest app.

But in both of the cases(*with or with out Pinterest app on my device*), I am able to Pin an image to my board and **request can not coming back to my app** and also it's always going to **failureBlock** even though I am giving valid credentials. May I know why it's happening like this?

*FYI, Your example app also behaves same as above.*

I already added below one to my plist file.

      <key>LSApplicationQueriesSchemes</key>
	<array>
		<string>pinterestsdk.v1</string>
	</array>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>pinimg.com</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
				<false/>
			</dict>
			<key>pinit</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
				<false/>
			</dict>
		</dict>
	</dict>

I have also defined redirect URI as pdk4792222935410545828 in my app.

Please help me on this issue and looking forward for your response.

Thanks,
Kayasiri.

**Comment by mkalmes** [comment]
Hey @kayasiri,

I guess @rcancro means [commit 21d1a4c](https://github.com/pinterest/ios-pdk/commit/21d1a4c8cdbb47046ef0d6e2568b9027ef2e1f5f) on master. Does this solves your problem?

FWIW: We currently although experience authentication errors with Safari and the Pinterest App on some devices.

**Comment by kayasiri** [comment]
If I am trying to integrate iOS-pdk in a new project using pod (*version 0.39.0*) by following your [documentation] (https://developers.pinterest.com/docs/sdks/ios/), But I am getting below error.
<img width="1415" alt="screen shot 2015-11-05 at 4 16 25 pm" src="https://cloud.githubusercontent.com/assets/1552756/10966317/d3e0a508-83d8-11e5-945d-ce8664c8a919.png">
Below is my Podfile

<img width="1433" alt="screen shot 2015-11-05 at 4 19 06 pm" src="https://cloud.githubusercontent.com/assets/1552756/10966353/12c62b58-83d9-11e5-8514-6c98fafe2a77.png">

So I saw #1 , changed my Podfile as below and now I am able to integrate iOS-pdk in my new project using pod. 

<img width="1433" alt="screen shot 2015-11-05 at 6 38 59 pm" src="https://cloud.githubusercontent.com/assets/1552756/10969164/93a8f274-83ec-11e5-8573-c2722ffc6d2c.png">

But there is no use because same errors (like oauth nil error if there is no Pinterest app on my device, no redirection to my app weather Pinterest app available or not) I am getting even now.

@mkalmes I have updated my Podfile to point to the [commit 21d1a4c] (https://github.com/pinterest/ios-pdk/commit/21d1a4c8cdbb47046ef0d6e2568b9027ef2e1f5f) as you suggested, but this is also not resolved my problem i.e. request not coming back to my app after successful Pin.

While performing authentication the request coming back to my app (weather it's success or failure, actually it's returning failure for valid credentials also),  then why request not coming back to my app for successful Pin also, just it's displaying success message as a Toast as shown in below image (at bottom left).

![img_0001](https://cloud.githubusercontent.com/assets/1552756/10969638/bf816086-83ef-11e5-87d7-85a2c2589fba.PNG)
 
FYI, I am using Xcode 7.1 & iPad with iOS 9.1

**Comment by kayasiri** [comment]
Hi Team,

Any response on this,  please give your comments on this in order to resolve this issue. 

Thanks,
Kayasri.

**Comment by kayasiri** [comment]
Hi Team,

Any response on this?

Thanks,
Kayasiri.

**Comment by parkerdonat** [comment]
@kayasiri  Double check to make sure your Bundle IDs match in your app and in your Pinterest App Developer page. For some reason found mine didn't match, I fixed it, and now my redirect works great.

**Comment by kayasiri** [comment]
Hi @parkerdonat 

Thank you for your response.

I have checked my Bundle IDs and I am maintaining same at my app and my Pinterest App Developer page. 

I have checked my app, now authentication working properly with out any issues in both cases (weather Pinterest app installed or not on my device) and redirecting to my authentication success block.

But still request not coming back after successful Pin if user is not having Pinterest app on device, could you please resolve this issue also.

Note: I have made all configurations at my app side as per your  [PinterestSDK for iOS Guide] ( https://developers.pinterest.com/docs/sdks/ios/)

Also you have to resolve #35 issue also.

Thanks & Regards,
Kayasiri.

**Comment by parkerdonat** [comment]
@kayasiri  Oh! I see your issue. Mine doesn't work either. I am sure they are working on a fix. They have been good at fixing issues. On the bright side, a lot of people have the Pinterest app installed already.

**Comment by kayasiri** [comment]
Thank you @parkerdonat for your response. I will be waiting for your fix. 

If possible, could you please update this issue status once it will be fixed.

Thanks & Regards,
Kayasiri.

**Comment by jijo009** [comment]
Is there is anyway to remove/hide third party login options (Facebook,Twitter,Google) from pinterest Oauth login screen. Currently I am having redirection issues with thridparty login services in IOS CNA browser. After the authentication pinterest API not redirecting back to the callback url. Sometimes it redirecting back to pinterest homepage and sometimes its got keep looping.

**Comment by NKorchagin** [comment]
Seems like this issue with redirecting back from **Safari** still not fixed. @rcancro could you please ping other teams (Front-end/MobileWeb/etc.) about it? Redirecting works ok from native application, but if it's not installed redirect is broken. Page just closed in Safari and do nothing. For our business goals when App used in Kiosk mode we would not like have Pinterest app installed on that devices. 

WebPage popup option with clear cookies like FB does will be the best option though, let me know if you're working on something similar to Facebook modal UIWebView pop up. 

And please, fix this redirect issue, it should be pretty easy. As I see from https://github.com/pinterest/ios-pdk/blob/master/Pod/Classes/PDKPin.m#L116 you did not send AppID to web page, that might be an issue.

**Comment by rcancro** [comment]
I can confirm that this is not working properly right now. We will redirect to Safari, but at that point we are using mobile web to pin, and it has no knowledge how we got there. I will have to talk with someone on the backend to see if they can provide this. I can't give a timeline as my guess is that it won't be a very high priority for anyone. 

With the move to SarfariViewController, the interaction on iOS9 is now a modal web VC opens in the client app, with a done button at the top left the user can tap when they have finished pinning. While this isn't ideal, it is probably the best solution that we will have for some time.

**Comment by TamilRaja** [comment]
I have also same issues came. Can you please suggest me. If any one fix this issues means update me. Follow the same tutorial but can not redirect to my app..
