### ISSUE TITLE
Describe how to install without CocoaPods.

### ISSUE THREAD

**Issue by bytor99999** [pinterest/ios-pdk#33]
So, I tried CocoaPods and while it works great. I don't want my app tied to it, so I never use it anymore. Carthage, in my mind is better. But still better is not using either. There are still some of us that would rather do it manually.

**Comment by garrettmoon** [comment]
You can simply download the files and add them to your project!

**Comment by bytor99999** [comment]
Thanks. That is how all frameworks should work. I just can never get any frameworks working in my projects. For instance, right now I have some embedded/linked copied into my project, even try "import" but the classes don't show up in my code.

Mark

**Comment by mrspeaker** [comment]
+1... I don't want to add a dependency on a dependency manager to integrate a third-party library.  It would be good if the "just download and add them to your project" approach was in the docs too!
