### ISSUE TITLE
Invalid URL Parameters with pinWithImageURL Method

### ISSUE THREAD

**Issue by parkerdonat** [pinterest/ios-pdk#34]
I'm trying to use the pinWithImageURL method, but the image doesn't show (causing an invalid URL) however, it does show and work correctly in Simulator. How do I ensure the imageURL is valid? Does the NSURL that Pinterest is expecting have a trick to it for images? 

I am using AmazonS3 and the imageURL appears to be valid: https://phototower.s3.amazonaws.com/2015-11-09%2018:18:53%20+0000.jpg

I did notice that the url doesn't open you have to manually save the image. If the image opened in a web URL would that make the imageURL valid?

Any help would appreciated. Thanks in advance.

**Comment by rcancro** [comment]
Looking into this. It looks like the content-type for this image is `Content-Type: application/x-www-form-urlencoded` whereas most images are something like `Content-Type: image/png`.

Not sure why s3 is serving it that way. You may want to look into that, a fix will involve a Pinterest client app change which could take a while :(

**Comment by parkerdonat** [comment]
@rcancro just wanted to say thank you. I fixed my content-type issues and that solved my issue. Thanks! I'm excited to release my app soon.
