### ISSUE TITLE
& Not Accepting In sourceURL and pinDescription When We Pin Using PinterestSDK in iOS

### ISSUE THREAD

**Issue by kayasiri** [pinterest/ios-pdk#35]
Hi Team,

I have integrated your ios-pdk in order to implement Pinterest sharing in my iOS App.

I am able to Pin an image successfully with out any issues if I am not having **&** either in pinDescription or in sourceURL.

If I am having **&** either in pinDescription or in sourceURL, then I am able to Pin image but with wrong pinDescription or sourceURL respectively. I already tried by encoding my pinDescription and sourceURL but there is no use. 

I am explaining a scenario below.

My **sourceURL** is *http://fortlauderdaledaily.com/pinit.php?id=23f0e617-c171-4f1d-b947-c56eaf571186&pn=149&pv=s* then Pinterest generated URL is :  

*pinterestsdk.v1://pinit/?app_name=Gold Coast&suggested_board_name=Magazine&image_url=http://files.parsetfss.com/2020f4b2-d5b6-47c4-b682-a03adc1d3646/tfss-57031e7f-ddeb-43d2-896f-f0ae74231db3-sampleFile&description=test&source_url=http://fortlauderdaledaily.com/pinit.php?id=23f0e617-c171-4f1d-b947-c56eaf571186&pn=149&pv=s&client_id=4792223395060121904*

and encoded URL is:

*pinterestsdk.v1://pinit/?app_name=Gold%20Coast&suggested_board_name=Magazine&image_url=http%3A%2F%2Ffiles.parsetfss.com%2F2020f4b2-d5b6-47c4-b682-a03adc1d3646%2Ftfss-57031e7f-ddeb-43d2-896f-f0ae74231db3-sampleFile&description=test&source_url=http%3A%2F%2Ffortlauderdaledaily.com%2Fpinit.php%3Fid%3D23f0e617-c171-4f1d-b947-c56eaf571186%26pn%3D149%26pv%3Ds&client_id=4792223395060121904*

After successful image Pin, If I click on **Visit Site** of my [Pin](https://www.pinterest.com/pin/488148047090241885/) , it's opening *http://fortlauderdaledaily.com/pinit.php?id=23f0e617-c171-4f1d-b947-c56eaf571186* only by truncating pn & pv keys.

I noticed that Pinterest truncating **&** from my sourceURL. But I want to Pin image with actual sourceURL i.e. *http://fortlauderdaledaily.com/pinit.php?id=23f0e617-c171-4f1d-b947-c56eaf571186&pn=149&pv=s* (pinDescription in future) with out any truncating. 

So How can I achieve this by using your Pinterest iOS SDK, please help me on this issue ASAP.

Thanks,
Kayasiri.

**Comment by josev55** [comment]
Maybe if you try to fully escape your source_url including the ampersands it would work.

**Comment by kayasiri** [comment]
Hi @josev55 ,

I already tried by encoding my source_url including the ampersands but it's not working.

Thank you for your response.
