### ISSUE TITLE
Redirect to My App Not Happening After Successful pinWithImageURL Method

### ISSUE THREAD

**Issue by parkerdonat** [pinterest/ios-pdk#37]
Hello, does not handle the automatic redirect back to my app when a pin is successful. I'm using the PDKPin pinWithImageURL method. When this method is called is the redirect suppose to happen automatically or is it manually by clicking the "< back to App" link in the top left of screen? The "< Back to app" link works in my app, but I thought the redirect was suppose to happen automatically. 

Any ideas on how to make this automatically redirect to my app? Here is my plist:

     <key>CFBundleDevelopmentRegion</key>
      <string>en</string>
        <key>CFBundleDisplayName</key>
       <string>${PRODUCT_NAME}</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>6</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLName</key>
			<string></string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>pdkMYAPPID</string>
			</array>
		</dict>
	</array>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>pinterestsdk.v1</string>
	</array>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>pinit</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
				<false/>
			</dict>
		</dict>
	</dict>
</dict>

P.S. I don't have any errors or anything just want to see if I can redirect users automatically after my pin is successful. Any help would be appreciated. Thanks!

**Comment by parkerdonat** [comment]
I'm so sorry. I just realized my Bundle ID was incorrect. Pinterest suggests using com.yourAppName.App but I realized mine was slightly different. The redirect works fine! :+1:

**Comment by Hema492** [comment]
I have added the same as suggested bundle id but it is not working. Please help it's urgent. Thanks.

**Comment by timonus** [comment]
I will see if I can repro.

**Comment by timonus** [comment]
I'm able to repro, will work on fixing for a future release of Pinterest iOS.

**Comment by Hema492** [comment]
Thanks a lot. If it is done I would be saved. :)

**Comment by timonus** [comment]
Following up, this is slated to be fixed in Pinterest iOS version 6.31.

**Comment by Hema492** [comment]
Thanks. Currently it is 6.30.
