### ISSUE TITLE
Possible crash due to codebase error

### ISSUE THREAD

**Issue by NKorchagin** [pinterest/ios-pdk#38]
https://github.com/pinterest/ios-pdk/blob/master/Pod/Classes/PDKPin.m#L135 
Could you please fix this line. It definitely should check for failure block here. With current implementation it will crash if we provide success block and skip failure block with nil. 

It also would be good to check all codebase for such errors, seems that there are also issues with successBlock inside AFNetworking operations. You should always keep in mind that developers may omit any block if they don't need them.

**Comment by rcancro** [comment]
Happy to accept a pull request!
