### ISSUE TITLE
Unable to get Pinterest App Id

### ISSUE THREAD

**Issue by kayasiri** [pinterest/ios-pdk#4]
Hi,

I am trying to integrate the Pinterest iOS SDK in my app. So I am trying get the Pinterest App Id by creating a new app at https://developers.pinterest.com/apps/, but till now I am not getting any App Id. I have created same app at https://developers.pinterest.com/manage/ and able to get App Id. If I use the App Id which I got at https://developers.pinterest.com/manage/, it's displaying an error in my console log like error: "This app is not allowed to query for scheme pinterestsdk.v1"  and also it' saying "Invalid Application ID".

I am getting below response when I am trying authenticate:
<b>{"status": "failure", "code": 283, "host": "coreapp-ngapi-prod-96e0647f", "generated_at": "Sat, 12 Sep 2015 08:01:37 +0000", "message": "The authorization grant is invalid", "data": "Invalid Application ID"}</b>

So could you please help me on this on how to get Pinterest App Id so that I will use that in my app.

Thanks,
Kayasiri.

**Comment by rcancro** [comment]
Hi Kayasiri,
https://developers.pinterest.com/apps/ is the correct place to apply for an app ID, but you have to wait for the app ID to be approved. The /manage/ endpoint is for legacy apps and doesn't work with the new SDK.

Thanks,
Ricky

**Comment by kayasiri** [comment]
Hi Ricky,

Thank you for responding, I have already applied for App Id at https://developers.pinterest.com/apps/ 4 days back but still there is no response from your side. May I know how much I need to wait and I need to wait only 1st app or every app?

Thanks,
Kayasiri.
