### ISSUE TITLE
ios 9 url scheme

### ISSUE THREAD

**Issue by braveS** [pinterest/ios-pdk#42]
Hello,
A month ago I used the next setting for Info.plist file
```
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>pinit12</string>
	</array>
```
and I was able to open concrete pin using such link
pinterest://pin/<17-digit-pin-number>
Right now it does not open the pint in app.
Could you please tell me: Is it still possible to open concrete pin in Pinterest application using deep linking mechanism?  (without pin sdk)

**Comment by rcancro** [comment]
We use the pinterest:// URL scheme internally to deep link into the app. We don't support 3rd party apps using that. 

The pinit://  URL scheme is part of the SDK. Setting it up for iOS9 is mentioned in the section `Using iOS9` in the docs https://developers.pinterest.com/docs/sdks/ios/. 

Take a look at the example app. If you tap on the "Pin it" button under authenticate you will be redirected to the Pinterest app in the pin-it flow. You can look at the SDK code to see what kind of URL that method creates.

Hope that helps.
