### ISSUE TITLE
Getting PDKPin.link

### ISSUE THREAD

**Issue by gesabo** [pinterest/ios-pdk#44]
I cannot find a property on PDKPin that returns a link to the Pin's source url (i.e. the website that you goto if you click the pin).  Per the docs this should be available?  https://developers.pinterest.com/docs/api/pins/

Looking at PDKPin.m it looks like this line
```_url = [NSURL URLWithString:dictionary[@"link"]];```
should be @"url" and

```_link = [NSURL URLWithString:dictionary[@"??????"]];```

should be added? 

Any help is appreciated, thank you!

**Comment by rcancro** [comment]
The source url is supposed the `url` property in `PDKPin`. 

The image url is in the `PDKImageInfo *image;` property.

**Comment by gesabo** [comment]
@rcancro I'm opening a new issue because I don't think I was clear.  The `url` property on `PDKPin` returns the internal Pinterest url of the pin, my question is I want to access the Pin's source URL, which the documentation describes as a `link` property.  It is writable via `pinWithImageURL` but not readable currently.
