### ISSUE TITLE
Crash, when user revokes access on the server

### ISSUE THREAD

**Issue by VilemKurz** [pinterest/ios-pdk#46]
User authenticates within the app (and trip to safari), all goes fine, token is in the keychain. Now user revokes access on the server. If want to check silently, if user is authenticated you call ```- (void)silentlyAuthenticateWithSuccess:(PDKClientSuccess)successBlock
                                 andFailure:(PDKClientFailure)failureBlock;``` the app (the sdk, more precisely) crashes at PDKClient line 208, because of inserting nil `permissionsString` into `params` dictionary.

**Comment by rcancro** [comment]
You did all the work! Could you submit a PR to fix this?
