### ISSUE TITLE
Please upload podspec file to the canonical Cocoapods/Specs repo

### ISSUE THREAD

**Issue by VilemKurz** [pinterest/ios-pdk#48]
Otherwise it is not possible to use your SDK as a dependency in other projects (podspecs), e.g in [ShareKit](https://github.com/sharekit/sharekit). In the case of ShareKit it means, that people do not have access to the Pinterest sharer if they install ShareKit via Cocoapods. I believe majority of ShareKit's users are using Cocoapods due to ease of use. [Here](https://guides.cocoapods.org/making/getting-setup-with-trunk.html) is a simple guide how to upload the podspec.

**Comment by ghugues** [comment]
+1

**Comment by rcancro** [comment]
You should be able to include the SDK with `pod "PinterestSDK", '1.0.1'` now. Please let me know if this isn't working.
