### ISSUE TITLE
Unable To Get Pinterest App Id

### ISSUE THREAD

**Issue by kayasiri** [pinterest/ios-pdk#5]
Hi ,

I have already applied for App Id at https://developers.pinterest.com/apps/ (as you said) 6 days back but still there is no response from your side. May I know how much time I need to wait and I need to wait only for 1st app or for every app?

I have already raised an issue #4 with same problem, but that ticket has been closed with out resolving my problem. Please let me know what is the problem and is there any thing I need to do from side ?

So please help me on this issue.

Thanks,
Kayasiri.

**Comment by kayasiri** [comment]
I thought Pinterest released an initial beta version of https://developers.pinterest.com/apps/ that's why there are some issue and unable to see my created apps. Now we are able to create new apps & also able to see them immediately but we need to wait till Pinterest approve our app to use their API.

Thanks,
Kayasiri.

**Comment by zackargyle** [comment]
We just released an update allowing general availability. Try again and you should be good to get going!
