### ISSUE TITLE
not getting largest image back on PDKBoard

### ISSUE THREAD

**Issue by gesabo** [pinterest/ios-pdk#52]
Whether I call largestImage or smallestImage on PDKBoard, they both seem to return the same thumbnail image (60x60) instead of the larger image with different dimensions.  Unless there something wrong with my dictionary call:   `["id", "image", "description", "name"]`

**Comment by gesabo** [comment]
Has anyone noticed this?  I'm calling `boards.largestImage().url` and getting a thumbnail.

**Comment by timle8n1** [comment]
Sounds like you may be running into the same I ran into - those calls don't work as the sorting for image size is broken. I've submitted a pull request.

https://github.com/pinterest/ios-pdk/pull/68

**Comment by rcancro** [comment]
PR merged. Sorry that this took so long.

**Comment by gesabo** [comment]
@timle8n1 have you tried this yet?  I'm still getting 60x60 image sizes on `board.largestImage` and `board.images`, not sure if I'm not requesting correctly?

**Comment by timle8n1** [comment]
Yup I wrote, tried, and using in my project. 

Quite possibly you are not getting the updated code, Pinterest hasn't been versioning the cocoa pod. You may need to delete your Pods directory in your project and the ~/Library/Caches/CocoaPods cache.

You can look at the source file to make sure the changes are actually in your project.

Also want image sizes are you requesting in your call? 

For instance my code is asking for the following fields:

` NSSet *fields = [NSSet setWithObjects:@"id", @"link", @"url", @"note", @"counts", @"image[640x, original]", nil];`

**Comment by gesabo** [comment]
Thanks tim, I did double check and my SDK code is up to date.  I can get the correct sizes on Pins, but I'm trying to get the Board Image or Images.  

This is my call `PDKClient.sharedInstance().getAuthenticatedUserBoardsWithFields(["id", "image", "name", "counts"]`

**Comment by timle8n1** [comment]
I think 60x60 is the default for board image. I'm sending "image[320x]" for my image field as I want board images that are 320x wide.

Put a breakpoint in the success callback and you can look at the JSON dictionary to see what image attributes you are getting.

**Comment by gesabo** [comment]
Oh ok, I missed that you were sending a size with your request.  Working now 👍🏻.  Thanks again!

**Comment by gesabo** [comment]
@timle8n1 where can I find the available sizes that I can request?  I couldn't find in the documentation?
