### ISSUE TITLE
Private boards missing in getAuthenticatedUserBoardsWithFields

### ISSUE THREAD

**Issue by hassanizhar** [pinterest/ios-pdk#55]

**Comment by connor** [comment]
@hassanizhar can you provide an example app where you're hitting the issue? Happy to take a look and help debug.

**Comment by hassanizhar** [comment]
By doing this I am getting only my public boards but missing secret boards

PDKClient.sharedInstance().authenticateWithPermissions([PDKClientReadPublicPermissions, PDKClientWritePublicPermissions, PDKClientReadPrivatePermissions, PDKClientWritePrivatePermissions, PDKClientReadRelationshipsPermissions, PDKClientWriteRelationshipsPermissions], withSuccess: { (object: PDKResponseObject!) -> Void in
//            print("pinterest authorized successfully")
            Util.showToast("Pinterest connected")
            PDKClient.sharedInstance().getAuthenticatedUserBoardsWithFields(NSSet(array: ["id","name"]) as Set<NSObject>, success: { (responseObject: PDKResponseObject!) -> Void in
                for object in responseObject.boards(){
                    let board = boardsModel()
                    board.boardName = object.name
                    board.boardId = (object.identifier)!!
                    self.boards.append(board)
                }

**Comment by gesabo** [comment]
My experience has been the same, even with all available permissions granted, I'm only getting pubic boards.

**Comment by hassanizhar** [comment]
@rcancro help me please.

**Comment by rcancro** [comment]
Looks like this is by design on the backend. :( From the docs, this is the description of what /v1/me/boards/ returns (emphasis is added by me): 

> The default response returns a list of the authenticated user’s **public** boards, including the URL, ID and name.

**Comment by mommyme** [comment]
It seems like this has changed in the latest version. Are we now allowed to allow our users to pin to secret boards? The official policy says that we are not, but it seems that we can do this in 1.0.2.
