### ISSUE TITLE
invalid client id

### ISSUE THREAD

**Issue by todaylover** [pinterest/ios-pdk#6]
I alway receive a "Parameter 'sdk_client_id' is not a valid client id" error. while my app has been approved.
Creating a pin was failed

Running the demo has the same error~

**Comment by todaylover** [comment]
anyone care this issue?

**Comment by rcancro** [comment]
Can you try updating your Podfile to point to the latest commit and see if the problem persists?

`pod 'PinterestSDK', :git => 'git@github.com:pinterest/ios-pdk.git', :commit => '4386ef09ee988de1f73511552fb3e35d721962b6'`

**Comment by todaylover** [comment]
@rcancro  unfortunate， this issue still exists

**Comment by todaylover** [comment]
@rcancro  in apps list, app status was approved, and in detail page the status is In development. If I submit review, the server response 500

**Comment by rcancro** [comment]
Point to the latest commit and this should be fixed.
`pod 'PinterestSDK', :git => 'git@github.com:pinterest/ios-pdk.git', :commit => '9cc111bc728a7c6dd9f1c77df01b18191685b62a'`
