### ISSUE TITLE
iOS redirect uri

### ISSUE THREAD

**Issue by dzolnjan** [pinterest/ios-pdk#60]
This is what docs are saying:

Registering Your App
Visit the Pinterest Developer Site and register your application. This will generate an appId for you which you will need in the next steps. Make sure to add your redirect URIs. For iOS your redirect URI will be pdk[your-appId]. For example, if you appId is 1234 your redirect URI will be pdk1234.

Where do I put this redirect value for iOS?

**Comment by connor** [comment]
@dzolnjan great question – sorry it wasn't clear.

You put this in the app's `Info.plist` file. This repo's `README` has an [example](https://github.com/pinterest/ios-pdk#configuring-xcode).
