### ISSUE TITLE
Share Multiple Images on pinterest.

### ISSUE THREAD

**Issue by muraribohra** [pinterest/ios-pdk#62]
Hello i want to share multiple images on pinterest. I dont get any documentation about this. Is this possible or not.
Thanks

**Comment by connor** [comment]
@muraribohra can you please clarify what you mean by "Share"? Create multiple Pins, Associate multiple images with one Pin, or something else?

**Comment by muraribohra** [comment]
I want to associate multiple images with one pin.

Sent from Yahoo Mail on Android 
 
  On Thu, Feb 25, 2016 at 7:48 PM, Connor Montgomery<notifications@github.com> wrote:   
@muraribohra can you please clarify what you mean by "Share"? Create multiple Pins, Associate multiple images with one Pin, or something else?

**Comment by connor** [comment]
Thanks for the feedback! This isn't possible yet (in the core product or PDKs), but will send your request along.
