### ISSUE TITLE
Getting PDKPin.link 

### ISSUE THREAD

**Issue by gesabo** [pinterest/ios-pdk#63]
#44 

The `url` property on `PDKPin` returns the internal Pinterest url of the pin, my question is I want to access the Pin's source URL, which the documentation describes as a `link` property.  It is writable via `pinWithImageURL` (see below) but not readable currently : 

```
+ (void)pinWithImageURL:(NSURL *)imageURL
                   link:(NSURL *)sourceURL
     suggestedBoardName:(NSString *)suggestedBoardName
                   note:(NSString *)pinDescription
            withSuccess:(PDKUnauthPinCreationSuccess)pinSuccessBlock
             andFailure:(PDKUnauthPinCreationFailure)pinFailureBlock
```

**Comment by gesabo** [comment]
If anyone has the chance can you please help me with this?  Until I can access the source URL, I'm forced to get the redirect myself which is really affecting performance of my app.
Thank you!

**Comment by connor** [comment]
@gesabo Unfortunately this SDK is inconsistent with our API docs (see #61). `pin.url` is the destination URL of the Pin; `pin.pinURL` is the `pinterest.com` URL of the pin. I think you are looking for `pin.url` with this SDK.

Does that answer your question?

**Comment by gesabo** [comment]
Thanks @connor for responding so quickly!  I'm calling pin.url here and this is what I'm getting: 

https://www.pinterest.com/r/pin/186195765822444484/4801566892554728205/532bb0b6e449fd7997efc1394c5f134906aaead1f04e44bfc722771d0ecd6671
https://www.pinterest.com/r/pin/186195765821108374/4801566892554728205/4b84455795601739d9a8cd52bbe6e6f9b257cfb32544c4a9f4cbc04fe6a232c4
https://www.pinterest.com/r/pin/186195765819695584/4801566892554728205/45e575fad22f149dae190d552c77e78ae1596fff8b8becdff111021b7fd1574c
https://www.pinterest.com/r/pin/186195765818872419/4801566892554728205/ab797a434824fdb80e22712a0cce102fa938fc27c1f9c5f0fd11e1f9362515cb

**Comment by gesabo** [comment]
On line 38 in the SDK 

` _url = [NSURL URLWithString:dictionary[@"link"]];` 

and I don't see anything that would pulldown the "url" ?

**Comment by connor** [comment]
@gesabo Apologies for the confusion. While those do link to `pinterest.com`, it's just a proxy to the destination URL that we have implemented for logging purposes.

**Comment by gesabo** [comment]
@connor ah, thank you.  Just so I'm clear then there's no way to get the pin's source url from the SDK currently?

**Comment by connor** [comment]
Correct – right now this is all that is publicly exposed. I'm talking w/ our dev-platform team to see if we'd be able to expose the underlying link but there are some logging implications, etc that we'd need to sort out before doing so. I'll post back here if I learn anything new!

**Comment by gesabo** [comment]
I'd really appreciate it!  Thanks again!
