### ISSUE TITLE
Can't install PinterestSDK pod after updating AFNetworking pod

### ISSUE THREAD

**Issue by Uki19** [pinterest/ios-pdk#65]
I am having trouble installing PinterestSDK after updating [AFNetworking](https://github.com/AFNetworking/AFNetworking) pod to it's latest version (3.0.4). Seems like PinterestSDK works only with AFNetworking version prior to 2.3.

Check screenshot from terminal bellow:
![image](https://cloud.githubusercontent.com/assets/9538239/13569309/9bb9c962-e467-11e5-9654-c1e66077c698.png)

**Comment by rcancro** [comment]
https://github.com/pinterest/ios-pdk/pull/82

**Comment by rcancro** [comment]
This change has been merged. If you use AFNetworking < 3, point your PinterestSDK pod to version 1.0.1. If you are using AFNetworking >= 3.0, point to version 1.0.2.
