### ISSUE TITLE
App getting crash while Pin the image

### ISSUE THREAD

**Issue by boomi1990** [pinterest/ios-pdk#69]
Hi,

I have configured the Pinterest SDK using Cocoapods. I am using Objective-C language. When I am calling the below block my app getting crashed. Please tell me how to solve this issue.

```
[PDKPin pinWithImageURL:[NSURL URLWithString:@"https://about.pinterest.com/sites/about/files/logo.jpg"] link:[NSURL URLWithString:@"https://www.pinterest.com"]
         suggestedBoardName:@"test"
                       note:@"The Pinterest Logo"
                withSuccess:^
     {
         // weakSelf.resultLabel.text = [NSString stringWithFormat:@"successfully pinned pin"];
     }
                 andFailure:^(NSError *error)
     {
         //weakSelf.resultLabel.text = @"pin it failed";
         
     }];

```
**Error:**

** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[3]'
*** First throw call stack:
(0x186260f5c 0x19ad67f80 0x18614f8e8 0x18614f780 0x1001eb9f0 0x100196e38 0x18b7ee3c8 0x18b7ee344 0x18b7d6c6c 0x18b7edc5c 0x18b7a8bdc 0x186217c30 0x1862159d4 0x186215e04 0x186144dc0 0x191298088 0x18b81ef44 0x100186c14 0x19b5928b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

Thanks
Boominadha Prakash M

**Comment by boomi1990** [comment]
Hi,

I solved this issue myself by adding Bundle display name in info.plist file. Now the app is not crashing.

Thanks,
Boominadha Prakash M

**Comment by fukemy** [comment]
hello. I facing this problem, but i can fill where the key "BundleDisplayName"

Page say: 
<key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLName</key>
      <string></string>
      <key>CFBundleURLSchemes</key>
      <array>
        <string>pdk{your-app-id}</string>
      </array>
    </dict>
  </array>
 So can you help me :)
