### ISSUE TITLE
Apple Rejection for SDK not implementing SafariViewController

### ISSUE THREAD

**Issue by gesabo** [pinterest/ios-pdk#70]
I received the below rejection.  My app (PinCheck) passed review before but now is getting rejected during an update... Apparently Apple is cracking down on this now? (i.e. wanting all web activity to take place inside the app) so I would assume other apps that use Pinterest's authentication may get rejected now as well? 

10.6 Details

We still notice that your app links to Safari for login or signup. 

Next Steps

Please revise your app to enable users to sign in or register an account in the app. 

We recommend implementing the Safari View Controller API to display web content within your app. The Safari View Controller allows the display of a URL and inspection of the certificate from an embedded browser in an app so that customers can verify the webpage URL and SSL certificate to confirm they are entering their sign in credentials into a legitimate page.

**Comment by gesabo** [comment]
Apple's response: 

Thank you for your response. We understand that Pinterest's SDK might only allow login through Safari but in order for your app to be compliant with guideline 10.6, you must allow users to stay within the app for signup and registration.

**Comment by gesabo** [comment]
I appealed my rejection and spoke to App Review today and they said that they are strictly enforcing in-app authentication now, I'll see what I can do myself but I'm not an Objective-C developer, if anyone else is working on a SafariViewController implementation please let me know.

**Comment by gesabo** [comment]
Thanks to @stanislaw, I forked temporary solution implementing SafariViewController here:  https://github.com/gesabo/ios-pdk

Note that this only supports IOS 9.0+, for compatibility with IOS 8.0 a WebView would be needed as well.

**Comment by nitsmanab** [comment]
Please check this Post:
[StackOverFlow Link](http://stackoverflow.com/a/39890022/2905967)
