### ISSUE TITLE
failed to import bridging header '/Users/hassanizhar/Desktop/Projects/ios/Research/CustomLibraries/CustomLibraries-Bridging-Header.h'

### ISSUE THREAD

**Issue by hassanizhar** [pinterest/ios-pdk#8]
![screen shot 2015-10-08 at 10 58 43 am](https://cloud.githubusercontent.com/assets/13674763/10358811/98a72112-6dab-11e5-8d07-b6d72313409c.png)

**Comment by hassanizhar** [comment]
I've declared @class UIImage at the top of PDKClient.h and this error was removed. Now I need help in createPinWithImageUrl in swift.

**Comment by rcancro** [comment]
What do you need help with? If you need help working with Objective-C in Swift, there are many resources available on the web.

**Comment by hassanizhar** [comment]
No resources found yet, that's why I asked.


Warm Regards,

Hassan Izhar





On Fri, Oct 9, 2015 at 9:52 AM -0700, "ricky" <notifications@github.com> wrote:
What do you need help with? If you need help working with Objective-C in Swift, there are many resources available on the web.

---

**Comment by garrettmoon** [comment]
Hi Hassan,

Check out the resources here:
https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/index.html#//apple_ref/doc/uid/TP40014216-CH2-ID0

Be sure to check the sections on Interoperability and Mix and Match. Good luck!

**Comment by hassanizhar** [comment]
I've already done those things.
