### ISSUE TITLE
API Status Degraded? 

### ISSUE THREAD

**Issue by gesabo** [pinterest/ios-pdk#87]
I filed a bug report, emailed support.  The API's status is showing as "degraded": https://developers.pinterest.com/docs/sdks/ios/. 

Since about 5pm EST on May 17th, I've been unable to access any pin urls from the /r directory: https://www.pinterest.com/r/pin/186195765818872419/4801566892554728205/ab797a434824fdb80e22712a0cce102fa938fc27c1f9c5f0fd11e1f9362515cb

My application pulls pins from this directory, so my app has been down for the same time frame. 

What's going on and will it be resolved soon? Thanks!

**Comment by zackargyle** [comment]
Hey Gary! Looks like it was a bug on our end on the developer site client app. The status is actually "UP". We got it fixed thanks to your issue. Thanks for reporting!

**Comment by arunranga** [comment]
@gesabo separately, we fixed a key-to-machine migration issue internally that caused 500 errors for the 'link' field returned by our API. So your link above works now :)

**Comment by gesabo** [comment]
@zackargyle @arunranga thanks for the quick response guys 😀
