### ISSUE TITLE
Problem with cocoapods (Unable to satisfy the following requirements:)

### ISSUE THREAD

**Issue by muraribohra** [pinterest/ios-pdk#9]
hi guyz, I am getting problem when i am installing pod file. error message is : 

[!] Unable to satisfy the following requirements:

- `PinterestSDK (from `git@github.com:pinterest/ios-pdk.git`)` required by `Podfile`

![image_6l](https://cloud.githubusercontent.com/assets/12935350/10361935/f0fe4c4c-6dc8-11e5-8b5c-fdedf3056d42.png)
![image_qo](https://cloud.githubusercontent.com/assets/12935350/10361934/f0fbef6a-6dc8-11e5-8f04-27f58161a059.png)
Please help me . 

Iam attaching POD file screenshot and terminal error message.

Thanks and regard.

**Comment by hassanizhar** [comment]
try this instead
pod ‘PinterestSDK', :git => 'https://github.com/pinterest/ios-pdk.git'

**Comment by muraribohra** [comment]
Thanks hassanizhar for reply, but i am still getting same error message. Ago two days i was successfully done this but from yesterday i am getting this message. Don't know whats going wrong.

**Comment by hassanizhar** [comment]
Welcome. I don't know why are they not responding to threads. Api has got issues and they need to fix it.

**Comment by rcancro** [comment]
I was able to install the pod using the same Podfile as you. What version of cocoapods are you running?

**Comment by muraribohra** [comment]
cocoapods-0.38.2

**Comment by muraribohra** [comment]
Ok guyz , Now i installed cocoapods 39.0 and set minimum deployment target 7.1 . Now it's works fine. This issue can be closed now. Thanks to all.

**Comment by the-scott-davis** [comment]
The comment from @hassanizhar worked for me
```
pod ‘PinterestSDK', :git => 'https://github.com/pinterest/ios-pdk.git'
```
