### ISSUE TITLE
No way to determine which of user's fetched boards are secret

### ISSUE THREAD

**Issue by mommyme** [pinterest/ios-pdk#94]
When user boards are fetched as a list, there is no way to determine which boards are secret and which are public. Yet all boards are fetched for the user, without being able to explicitly include/exclude secret or public boards. In many use cases for fetching a user's board list, I feel like it is important to be able to determine/show the user which boards are secret and which boards are public.

Additionally, it would be a nice feature to allow a user to create secret boards within an app, as long as the user can specify explicitly (i.e. through a  switch) that the board should be secret.

**Comment by gesabo** [comment]
You are able to pull private boards?  I can only pull public:  https://github.com/pinterest/ios-pdk/issues/55

**Comment by gesabo** [comment]
Did something in the SDK change to make private boards available?  I request `PDKClientReadPrivatePermissions`  but I am still only getting public.

**Comment by mommyme** [comment]
When I run the sample app with my account it pulls back all of my boards, including secret. Which is great - I just have no way to tell which is which for the users. Tell me if I am mistaken here...

**Comment by gesabo** [comment]
Can you list your permissions @mommyme ?  My private boards still don't show and here is my call: 

 ```
let permissions = [PDKClientReadPublicPermissions,
                    PDKClientWritePublicPermissions,
                    PDKClientReadPrivatePermissions,
                    PDKClientWritePrivatePermissions,
                    PDKClientReadRelationshipsPermissions]
```

**Comment by mommyme** [comment]
@gesabo I thought I had plugged my app ID into the sample app because the ids look a lot alike. When I plugged my actual ID into the sample app, I could not see the secret boards. The sample app must have special permissions. I wish that I knew how to go about requesting those permissions. Anyone from Pinterest have an idea? It would be such an awesome feature (and also the ability to know which boards are secret). I know it would really enhance my users' experience in my app to have the ability to keep the boards they create through the app secret if they chose to. Thanks for the API in general - love it - and thanks if you can help at all with this.

**Comment by jparise** [comment]
I added (in 0d57c37) a `privacy` property to `PDKBoard` objects that indicate whether the board is "public" or "private". The example application has also been updated to show how that can be used.

I afraid we don't currently support creating private boards or filtering the board list through the developer API.

**Comment by mommyme** [comment]
Thanks Jon. If we can't create private boards, is there a way we can get permission to at least pull the private boards when we query the list of all user boards within an app? It seems that the sample app has that permission, but my development app does not. To be clear, if I just want to have a user pin within the Pinterest app (one option for creating pins), I do see the list of all the boards within Pinterest. But when I query to get all of a user's boards within my development app, I can only get the public (non-secret) boards. 

I feel like the more options I give my users regarding Pinterest, the more likely they are to use that feature within my app (it is just a small part of the app, but one that I think would really enhance it). Is there a way to request private permissions, perhaps based on the number of users an app currently has, or some other criteria determined by Pinterest?

**Comment by arunranga** [comment]
@mommyme : we've removed write_private and read_private from the SDK for now. You'll note that this makes the SDK consistent with stuff like our API Explorer (https://developers.pinterest.com/tools/api-explorer/) and with our developer docs in general.

I think we're also going to evaluate our OAuth permissions in general. It's not unlikely that after some product-level thinking about private boards we'll reintroduce the permissions. I really like your suggestion about determining criteria through which to release private board information, including possibly # users or something else (possibly by use case).

**Comment by gesabo** [comment]
@arunranga just to chime in on this issue, I have an app that's a utility that checks Pinterest boards for broken links  https://itunes.apple.com/us/app/pincheck-check-your-pins-for/id1076132529?mt=8 and the utility of the app would obviously benefit by being able to check all boards ...just wanted to add a use case example where a user might want to grant access to private boards.

**Comment by jonny5** [comment]
@arunranga any update on if `read_private` on your guys' roadmap for the API?

**Comment by mommyme** [comment]
@arunranga Do you have any updates about private boards? I would like to integrate the API, but cannot do it until users have the option to create private boards from within the app. Thanks.
