### ISSUE TITLE
Error while posting image

### ISSUE THREAD

**Issue by Tom29** [pinterest/ios-pdk#97]
I follow the instruction and still get this error

> Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x1380236c0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=pins/, NSErrorFailingURLKey=pins/, NSLocalizedDescription=unsupported URL}

**Comment by OlegPanfyorov** [comment]
Got the same issue :(
